"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CEDScreen = exports.CEDBoolean = exports.CEDItemTypes = exports.CEDCategories = exports.ExternalPaymentTypes = exports.EntryModes = exports.PaymentTypes = exports.TransactionTypes = void 0;
var TransactionTypes;
(function (TransactionTypes) {
    TransactionTypes["SALE"] = "SALE";
    TransactionTypes["AUTHORIZATION"] = "AUTHORIZATION";
    TransactionTypes["REFUND"] = "REFUND";
    TransactionTypes["ADDVALUE"] = "ADDVALUE";
    TransactionTypes["BALANCEINQUIRY"] = "BALANCEINQUIRY";
})(TransactionTypes = exports.TransactionTypes || (exports.TransactionTypes = {}));
var PaymentTypes;
(function (PaymentTypes) {
    PaymentTypes["VISA"] = "VISA";
    PaymentTypes["MASTERCARD"] = "MASTERCARD";
    PaymentTypes["AMEX"] = "AMEX";
    PaymentTypes["DISCOVER"] = "DISCOVER";
    PaymentTypes["DEBIT"] = "DEBIT";
    PaymentTypes["GIFT"] = "GIFT";
    PaymentTypes["EBT"] = "EBT";
    PaymentTypes["LEVELUP"] = "LEVELUP";
    PaymentTypes["VOYAGER"] = "VOYAGER";
    PaymentTypes["WEX"] = "WEX";
    PaymentTypes["JCB"] = "JCB";
    PaymentTypes["CUP"] = "CUP";
    PaymentTypes["UNKNOWN"] = "UNKNOWN";
})(PaymentTypes = exports.PaymentTypes || (exports.PaymentTypes = {}));
var EntryModes;
(function (EntryModes) {
    EntryModes["SWIPE"] = "SWIPE";
    EntryModes["PROXIMITY"] = "PROXIMITY";
    EntryModes["BARCODE"] = "BARCODE";
    EntryModes["MANUAL"] = "MANUAL";
})(EntryModes = exports.EntryModes || (exports.EntryModes = {}));
var ExternalPaymentTypes;
(function (ExternalPaymentTypes) {
    ExternalPaymentTypes["Cash"] = "Cash";
    ExternalPaymentTypes["Check"] = "Check";
    ExternalPaymentTypes["StoreCredit"] = "StoreCredit";
    ExternalPaymentTypes["Other"] = "Other";
})(ExternalPaymentTypes = exports.ExternalPaymentTypes || (exports.ExternalPaymentTypes = {}));
var CEDCategories;
(function (CEDCategories) {
    CEDCategories["None"] = "None";
    CEDCategories["Ebt"] = "Ebt";
    CEDCategories["Fuel"] = "Fuel";
})(CEDCategories = exports.CEDCategories || (exports.CEDCategories = {}));
var CEDItemTypes;
(function (CEDItemTypes) {
    CEDItemTypes["Sku"] = "Sku";
    CEDItemTypes["Misc"] = "Misc";
})(CEDItemTypes = exports.CEDItemTypes || (exports.CEDItemTypes = {}));
var CEDBoolean;
(function (CEDBoolean) {
    CEDBoolean["True"] = "true";
    CEDBoolean["False"] = "false";
})(CEDBoolean = exports.CEDBoolean || (exports.CEDBoolean = {}));
var CEDScreen;
(function (CEDScreen) {
    CEDScreen["Idle screen"] = "00";
    CEDScreen["Validating TransportKey"] = "01";
    CEDScreen["Main payment collection"] = "02";
    CEDScreen["Custom payment collection"] = "03";
    CEDScreen["Looking up card BIN"] = "04";
    CEDScreen["Waiting for amount confirmation"] = "05";
    CEDScreen["Waiting for PIN entry"] = "06";
    CEDScreen["Processing payment"] = "07";
    CEDScreen["Waiting for signature"] = "08";
    CEDScreen["Processing signature capture"] = "09";
    CEDScreen["Transaction result"] = "10";
    CEDScreen["Cancel confirmation"] = "11";
    CEDScreen["Run as credit confirmation"] = "12";
    CEDScreen["SKU display"] = "13";
    CEDScreen["Cashback selection screen"] = "14";
    CEDScreen["Cashback custom screen"] = "15";
    CEDScreen["Tip selection screen"] = "16";
    CEDScreen["Tip custom screen"] = "17";
    CEDScreen["Donation selection screen"] = "18";
    CEDScreen["Donation custom screen"] = "19";
    CEDScreen["Confirmation screen"] = "20";
    CEDScreen["Error screen"] = "24";
    CEDScreen["SKU amount confirmation screen"] = "26";
    CEDScreen["PAN entry screen"] = "27";
    CEDScreen["Expiration entry screen"] = "28";
    CEDScreen["CVV entry screen"] = "29";
    CEDScreen["Zip entry screen"] = "30";
    CEDScreen["Agreement screen"] = "31";
    CEDScreen["Agreement signature screen"] = "32";
    CEDScreen["EMV application selection screen"] = "33";
    CEDScreen["Get customer input screen"] = "35";
    CEDScreen["Gift card capture screen"] = "36";
    CEDScreen["Network details screen"] = "38";
    CEDScreen["Network configuration screen"] = "39";
})(CEDScreen = exports.CEDScreen || (exports.CEDScreen = {}));
